source("best.R")

best("TX", "heart attack")
best("TX", "heart failure")
best("MD", "heart attack")
best("MD", "pneumonia")
best("BB", "heart attack")
best("NY", "hert attack")
best("MD", "heart attack")
best("TX", "heart failure")
best("MD", "pneumonia")
best("SC", "heart attack")
best("NY", "pneumonia")
best("AK", "pneumonia")

