source("rankhospital.R")

rankhospital("TX", "heart attack", 12)
rankhospital("TX", "heart attack")
rankhospital("TX", "heart attack", 1)
rankhospital("TX", "heart failure", "best")
rankhospital("TX", "heart failure", "besst")
rankhospital("TX", "heart failure", "worst")
rankhospital("TX", "heart failure", 295)
rankhospital("MD", "heart attack")
rankhospital("MD", "pneumonia")
rankhospital("BB", "heart attack")
rankhospital("NY", "hert attack")
rankhospital("MD", "heart attack")
rankhospital("TX", "heart failure")
rankhospital("MD", "pneumonia")
rankhospital("TX", "heart failure", 4)
rankhospital("MD", "heart attack", "worst")
rankhospital("MN", "heart attack", 5000)
rankhospital("NC", "heart attack", "worst")
rankhospital("WA", "heart attack", 7)
rankhospital("TX", "pneumonia", 10)
rankhospital("NY", "heart attack", 7)
